# Generated by Django 3.0.9 on 2020-08-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='challenges_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=1, verbose_name=range(1, 6)),
        ),
        migrations.AlterField(
            model_name='user',
            name='vote_given_to',
            field=models.CharField(max_length=100),
        ),
    ]
